services:
  - type: web
    name: igris-server
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o igris-server server.go
    startCommand: ./igris-server
    envVars:
      - key: PORT
        value: 80